spring:
  application:
    name: AppList

  # Configuración de la Base de Datos (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/db_applist?serverTimezone=America/Lima
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Configuración de JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate   # ¡Modificado para producción!
    show-sql: false        # ¡Modificado para producción!
    properties:
      hibernate:
        format_sql: false  # ¡Modificado para producción!
        jdbc:
          lob:
            non_contextual_creation: true

# APIS Externas
tmdb:
  api:
    url: https://api.themoviedb.org/3
    token: ${TMDB_TOKEN}

google:
  books:
    api:
      key: ${GOOGLE_BOOKS_KEY}

rawg:
  api:
    url: https://api.rawg.io/api
    key: ${RAWG_API_KEY}

# Seguridad
jwt:
  secret: ${JWT_SECRET}
  expiration: 10368000000