server:
  port: ${PORT:8080}

spring:
  application:
    name: AppList

  # Desactiva la intercepción automática de compose.yaml en desarrollo
  docker:
    compose:
      enabled: false

  # Configuración de la Base de Datos (PostgreSQL)
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Configuración de JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # por ahora para supabase
    show-sql: false        # ahorro de logs de memoria para produccion
    properties:
      hibernate:
        format_sql: false  # ahorro de logs de memoria para produccion
        jdbc:
          lob:
            non_contextual_creation: true

# APIS Externas
tmdb:
  api:
    url: https://api.themoviedb.org/3
    token: ${TMDB_TOKEN}

google:
  books:
    api:
      key: ${GOOGLE_BOOKS_KEY}

rawg:
  api:
    url: https://api.rawg.io/api
    key: ${RAWG_API_KEY}

# Seguridad
jwt:
  secret: ${JWT_SECRET}
  expiration: 10368000000